### ISSUE TITLE
PLGSharepointClientOnline.updateFileMetadata wrong type

### ISSUE THREAD

**Issue by waldimiro** [kikovalle/PLGSharepointRestAPI-java#10]
Hi, I'm playing with your code. Please check on PLGSharepointClientOnline.updateFileMetadata the meta.put("type", "SP.Folder"); line. Must not be meta.put("type", "SP.ListItem"); ?

**Comment by kikovalle** [comment]
Hi, i'll double check what you are telling but there are different api
urls, one is for lists and other for files / folders. The use of
SP.ListItem or SP.Folder or SP.File depends on the api method you are
invoking.
But as i say ill check it and write back you once i verify the api url that
is called in that method

**Comment by kikovalle** [comment]
Even if i have not tested this with SP.ListItem type, if you look at the rest api call, in that concrete case it is using the file api /_api/web/GetFileByServerRelativeUrl and this rest method don't know about lists, so the correct types here may be SP.File or SP.Folder, depends if you are updating a file or a folder (a folder is also a file at operating system level)
Like when you upload an item to a list the type may be SP.ListItem (as the rest api used is the list api) in this case it may be SP.Folder or SP.File, as SP.ListItem  has nothing to do with files, is an element inside a list. Its a bit confusing but is a matter of which endpoint is called in the sharepoint rest api. (ill test if it works with SP.ListItem as it can be a more abstract type that can cover files and folders in case it works with this call.

**Comment by kikovalle** [comment]
Related to issue https://github.com/kikovalle/PLGSharepointRestAPI-java/issues/17
Fixed in commit 6db5f73 . If metadata payload passes to method contains type then that type will be sent to sharepoint.
