### ISSUE TITLE
App only authentication

### ISSUE THREAD

**Issue by jh3129** [kikovalle/PLGSharepointRestAPI-java#13]
Hi there, do you know if this supports app-only authentication? So, using a client id and password only?

**Comment by kikovalle** [comment]
Hello

This API only implements user / pass authentication to use sharepoint rest
api. You can achieve that kind of auth with the microsoft graph APIs.

Regards

**Comment by jh3129** [comment]
I see – that’s more or less a complete re-write?

**Comment by kikovalle** [comment]
graph apis are based in azure services, not directly sharepoint rest apis
(as far as i know) sow the answer is yes, it may be a complete refactor of
the code.

**Comment by jh3129** [comment]
I would have thought you could change the header content in order to supply the client id/secret?

**Comment by kikovalle** [comment]
Feature added with commit #24
