### ISSUE TITLE
Initialization failed!! Please check the user, pass, domain and spSiteUri parameters you provided

### ISSUE THREAD

**Issue by fergcody** [kikovalle/PLGSharepointRestAPI-java#14]
Needed to use on premises class. Working now. Great job!

**Comment by fergcody** [comment]
Working now

**Comment by kikovalle** [comment]
Sorry not answering before as i am a bit busy at work this days.
Xxxxxx.sharepointonline.com as domain
User@domain.com for user
Userpass for passeord
/Sites/yoursite/ for the spsiteurl

Hope this help you to solve the issue and sorry again for the delay in
response
