### ISSUE TITLE
XML resereved characters in user password

### ISSUE THREAD

**Issue by vnashkev** [kikovalle/PLGSharepointRestAPI-java#16]
If user password parameter contains one of xml-resereved characters then api call fails with NullPointerException.

`PLGSharepointClient wrapper = new PLGSharepointClientOnline(user, "p&ssword", domain, spSiteUrl);
wrapper.getFolderFilesByRelativeUrl(base, "{ }");
`
I think xml-reserved characters at least for password parameter must be escaped.

[xml predefined entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references)

Thank you in advance, 
Vitali

**Comment by vnashkev** [comment]
It seems the easiest solution is to wrap password with  `<![CDATA[ ]]>` section in definition of 
`AuthTokenHelperOnline.payload` member
`...
<o:Password><![CDATA[%s]]></o:Password>
...
`

**Comment by kikovalle** [comment]
Thank you for the help. I had no time yesterday and today as i was busy at
work. I'll try to commit a fix today.

Thank you

**Comment by kikovalle** [comment]
Commited fix in commit 488b0b5b0c82a5c852b4550ce7f3a95f8c8ce444 . Added CDATA inside xml tag username and password to solve the login error with xml characters in login.
