### ISSUE TITLE
Customize Type for multi choice Fields

### ISSUE THREAD

**Issue by uwohlfeil** [kikovalle/PLGSharepointRestAPI-java#17]
I have a document list with a metadatafield, which is configured as Multi choise field. In this case, it is important to set the correct type.

I have to set the type like this:
`{"ContractpartnerId":{"results":[2]},"__metadata":{"type":"SP.Data.MyContractItem"}}`

If it is set to SP.ListItem, I received the error message:
`{
  "error": {
    "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
    "message": {
      "lang": "en-US",
      "value": "An open collection property 'ContractpartnerId' was found. In OData, open collection properties are not supported."
    }
  }
}`

Is it possible, to set the type optionally to a custom type if required?

Currently, it seems to be hard coded.
[UploadFile Function](https://github.com/kikovalle/PLGSharepointRestAPI-java/blob/efc9baaa3af094d0b7dc938d3017600f5f174706/src/main/java/com/panxoloto/sharepoint/rest/PLGSharepointOnPremisesClient.java#L429)

Maybe just change it to:
`	
if(!jsonMetadata.has("__metadata")){
   JSONObject submeta = new JSONObject();
   submeta.put("type", "SP.ListItem");
   jsonMetadata.put("__metadata", submeta);
}`

**Comment by kikovalle** [comment]
Thanks for your feedback. I'll review the api to provide a way to overwrite
the default element type.

**Comment by kikovalle** [comment]
Fixed in commit 6db5f734af857b33f6fa3e08f2114a067a257f8c . If metadata payload passes to method contains type then that type will be sent to sharepoint.
