### ISSUE TITLE
SEVERE: Initialization failed!! Please check the user, pass, domain and spSiteUri parameters you provided

### ISSUE THREAD

**Issue by immanuel2112** [kikovalle/PLGSharepointRestAPI-java#2]
Hi,

I am getting this following error when trying to run this program. I checked all parameter and they are valid. 

Request Entity is fine. But reponse entity is having this message due to which securityToken.indexOf(clave1) is failing with java.lang.StringIndexOutOfBoundsException: String index out of range: -1.

This is the content of ResponseEntity & SecurityToken values.

Let me know what am I missing.

**responseEntity:**
<200,<?xml version="1.0" encoding="utf-8"?><S:Envelope xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust" xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Header><psf:pp xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><psf:serverVersion>1</psf:serverVersion><psf:authstate>0x80048800</psf:authstate><psf:reqstatus>0x80048821</psf:reqstatus><psf:serverInfo ServerTime="2020-07-22T08:06:13.9354531Z">PROD-DUB2-010.ProdSlices rid:1203662d-bed0-4d8b-b377-a9f80f0f4c00</psf:serverInfo></psf:pp></S:Header><S:Body xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Fault><S:Code><S:Value>S:Sender</S:Value><S:Subcode><S:Value>wst:FailedAuthentication</S:Value></S:Subcode></S:Code><S:Reason><S:Text xml:lang="en-US">Authentication Failure</S:Text></S:Reason><S:Detail><psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><psf:value>0x80048821</psf:value><psf:internalerror><psf:code>0x80048821</psf:code><psf:text>**AADSTS50126: Error validating credentials due to invalid username or password.**</psf:text></psf:internalerror></psf:error></S:Detail></S:Fault></S:Body></S:Envelope>,[Cache-Control:"no-cache, no-store", Pragma:"no-cache", Content-Type:"application/soap+xml; charset=utf-8", Expires:"-1", Strict-Transport-Security:"max-age=31536000; includeSubDomains", X-Content-Type-Options:"nosniff", x-ms-request-id:"1203662d-bed0-4d8b-b377-a9f80f0f4c00", x-ms-ests-server:"2.1.10858.13 - DUB2 ProdSlices", P3P:"CP="DSP CUR OTPi IND OTRi ONL FIN"", Set-Cookie:"fpc=AlR-_K_q869GqDCmaMqrM9aApSWjAQAAAHTqqdYOAAAA; expires=Fri, 21-Aug-2020 08:06:13 GMT; path=/; secure; HttpOnly; SameSite=None", "x-ms-gateway-slice=prod; path=/; SameSite=None; secure; HttpOnly", "stsservicecookie=ests; path=/; SameSite=None; secure; HttpOnly", Date:"Wed, 22 Jul 2020 08:06:13 GMT", Content-Length:"1430"]>

**Security Token:**
<?xml version="1.0" encoding="utf-8"?><S:Envelope xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust" xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Header><psf:pp xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><psf:serverVersion>1</psf:serverVersion><psf:authstate>0x80048800</psf:authstate><psf:reqstatus>0x80048821</psf:reqstatus><psf:serverInfo ServerTime="2020-07-22T08:06:13.9354531Z">PROD-DUB2-010.ProdSlices rid:1203662d-bed0-4d8b-b377-a9f80f0f4c00</psf:serverInfo></psf:pp></S:Header><S:Body xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Fault><S:Code><S:Value>S:Sender</S:Value><S:Subcode><S:Value>wst:FailedAuthentication</S:Value></S:Subcode></S:Code><S:Reason><S:Text xml:lang="en-US">**Authentication Failure**</S:Text></S:Reason><S:Detail><psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><psf:value>0x80048821</psf:value><psf:internalerror><psf:code>0x80048821</psf:code><psf:text>**AADSTS50126: Error validating credentials due to invalid username or password.**</psf:text></psf:internalerror></psf:error></S:Detail></S:Fault></S:Body></S:Envelope>

**Comment by kikovalle** [comment]
Hello, as you can see in the error the error is related to invalid credentials (invalid username or password). Can you provide me the full stack trace of the exception being logged by the API?
The credentials are a valid username (user email that has access to the sharepoint site and permissions to use the rest api) and password for your sharepoint site. And the domain may be something like something.sharepoint.com.
The exception is related to a invalid login, so after that is impossible to retrieve a valid token so you may see an exception.
