### ISSUE TITLE
Authentification Failure while trying to login with userID and password (2 factor authentification) issue?

### ISSUE THREAD

**Issue by BenediktLueth** [kikovalle/PLGSharepointRestAPI-java#21]
Hey kikovalle,

I've checked my Sharepoint Mail-Address and my Sharepoint Domain, but I still get an authentification failure exception when I'm trying to create your wrapper PLGSharepointClientOnline.

I just provided my password additionally. Nothing works. I've checked for several hours. 

When I was trying to Logout from Sharepoint and Login again with that userID and that Domain I've was asked for a second factor authentification via my smartphone. Is this the reason, why your wrapper ist not working? Do you have an suggestion what workaround will work? Do I need a technical user without 2FA? 

Thank you so much. I wish you best!

Benedikt

**Comment by kikovalle** [comment]
Hello

RIght now the API doesnt work with 2FA, For API to work you need an user
who can login to sharepoint with user / password.  As you said the easiest
way to make it work is to have an user with 2FA disabled to be used from
API.

Thank you, best regards
