### ISSUE TITLE
Maven Central?

### ISSUE THREAD

**Issue by cpesch** [kikovalle/PLGSharepointRestAPI-java#28]
Are there any plans to publish to maven central? It makes build pipelines a lot easier.

**Comment by kikovalle** [comment]
I will look forward trying to publish it as it will make easier the import and usage, and also easier fix / updates distribution.

Ill keep you informed

**Comment by kikovalle** [comment]
Finally after some time trying to make github action to work artifacts are deployed to maven central in this repo

https://s01.oss.sonatype.org/#view-repositories;releases~browsestorage~io/github/kikovalle/com/panxoloto/sharepoint/rest/PLGSharepointRestAPI

		<dependency>
			<groupId>io.github.kikovalle.com.panxoloto.sharepoint.rest</groupId>
			<artifactId>PLGSharepointRestAPI</artifactId>
			<version>1.0.3</version>
		</dependency>

**Comment by cpesch** [comment]
Works fine, thank you!
