### ISSUE TITLE
Office 365 403 

### ISSUE THREAD

**Issue by LipcseiZsolt** [kikovalle/PLGSharepointRestAPI-java#3]
Hi!

Thank you for your work! I'm using office365 account and when I try to create folder or upload file I get 403 code as response. And  GET methods give me 500 error.

**Comment by kikovalle** [comment]
Hello

I hope it will be helpful for someone :)

For the first 403 error that is a permission related issue, it means that
for some reason server understood your request but there is a permission
related problem. The user may have Collaborator or Full Permission on list
to be able to create /update/delete folders. You can try to create a folder
in the sharepoint library with the same user you connect with the API and
in the same library from the web browser (if you cant then youll have to
give permissions to that user in the list so it will be able to create
folders).

For the second error on get methods take a look of this working test (i
cant provide access credentials).

String spSiteUrl = "/sites/{FULL_URI_PATH_OF_YOUR_SP_SITE}";
String user = "user@domaincom";
String passwd = "YOURUSERPASSWORD";
String domain = "sharemointsitedomainname"; // like "
mysharepoint.sharepoint.com" without protocol

@Test
void testGetListItemsFiltered() {
PLGSharepointClient wrapper = new PLGSharepointClient(user, passwd, domain,
spSiteUrl);
try {
String queryStr = "$filter=YOURFIELDNAME eq 'YOURFIELDVALUE'";
JSONObject result = wrapper.getListItems("{LISTNAME}", "{}", queryStr); //
listname is the name of the list without the path to it
System.out.println(result);
Assert.assertTrue(result != null);
} catch (Exception e) {
// TODO Auto-generated catch block
e.printStackTrace();
Assert.assertTrue(false);
}
}

Hope this will solve your issues

**Comment by LipcseiZsolt** [comment]
Thank you for the quick answer. Altough it wasn't helpful to me. I tried to login with a full permission user, but I tstil got 403 code.

**Comment by kikovalle** [comment]
Hi
The 403 error code means that there is something wrong with your user
permissions.
You can take a look of this posts in stackoverflow
https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses

Receiving a 403 response is the server telling you, “I’m sorry. I know who
you are–I believe who you say you are–but you just don’t have permission to
access this resource. Maybe if you ask the system administrator nicely,
you’ll get permission. But please don’t bother me again until your
predicament changes.”

Sharepoint manage its own permissions for each site and each library in a
site, so you may check that the user has permissions. I've tested code
several times with more than one user (as i use this api in some of my job
projects) and is working fine.

**Comment by LipcseiZsolt** [comment]
It's working fine now, the problem was with the URL. Sorry for waste your time. :(

**Comment by kikovalle** [comment]
No problem.I think m$ can do a better job in some of their products documentation. Hope the code will be helpfull for you. Also feel free to ask for improvements in functionallity.
