### ISSUE TITLE
How to filename when uploading

### ISSUE THREAD

**Issue by DarioJahnel** [kikovalle/PLGSharepointRestAPI-java#32]
Hi! first of all thank you for this library, super easy to use!

How can I can I set the filename I upload? I tried doing this (sharepoint site is in spanish)

```
JSONObject payload = new JSONObject();
payload.put("Nombre", nombreArchivo);
payload.put("nombre", nombreArchivo);
payload.put("name", nombreArchivo);
payload.put("Name", nombreArchivo);
JSONObject result = wrapper.uploadFile(spSiteUrl + spFolder + spBackupFolder, archivo, payload);
```

but it always uploads the file as "null"
![image](https://user-images.githubusercontent.com/40502503/140084997-53744f6f-1dd3-40a6-a1a0-409e2a94c4a0.png)
![image](https://user-images.githubusercontent.com/40502503/140085033-7328173d-a365-4fb1-87be-fd73f612dbc4.png)

**Comment by kikovalle** [comment]
This method was added to fix that problem:
/**
	 * @param folder
	 * @param resource
	 * @param fileName
	 * @param jsonMetadata
	 * @return
	 * @throws Exception
	 */
	JSONObject uploadFile(String folder, Resource resource, String fileName, JSONObject jsonMetadata) throws Exception;


Where fileName is the final name of the upload file.
