### ISSUE TITLE
Multi-factor authentication issue

### ISSUE THREAD

**Issue by alex93jansen** [kikovalle/PLGSharepointRestAPI-java#4]
Hi, when running my program I'm receiving the following error:

`[main] ERROR com.panxoloto.sharepoint.rest.PLGSharepointClient - Initialization failed!! Please check the user, pass, domain and spSiteUri parameters you provided`

with the following value for **responseEntity**:

`<200,<?xml version="1.0" encoding="utf-8"?><S:Envelope xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust" xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Header><psf:pp xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><psf:serverVersion>1</psf:serverVersion><psf:authstate>0x80048800</psf:authstate><psf:reqstatus>0x800434d4</psf:reqstatus><psf:serverInfo ServerTime="2020-08-24T20:45:06.2266655Z">PROD-SAN-012.ProdSlices rid:9a469a67-57dc-4f63-8c32-94a07e9d9f00</psf:serverInfo></psf:pp></S:Header><S:Body xmlns:S="http://www.w3.org/2003/05/soap-envelope"><S:Fault><S:Code><S:Value>S:Sender</S:Value><S:Subcode><S:Value>wst:FailedAuthentication</S:Value></S:Subcode></S:Code><S:Reason><S:Text xml:lang="en-US">Authentication Failure</S:Text></S:Reason><S:Detail><psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><psf:value>0x800434D4</psf:value><psf:internalerror><psf:code>0x800434D4</psf:code><psf:text>AADSTS50076:` **Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access ''**.`</psf:text></psf:internalerror></psf:error></S:Detail></S:Fault></S:Body></S:Envelope>,[Cache-Control:"no-store, no-cache", Pragma:"no-cache", Content-Type:"application/soap+xml; charset=utf-8", Expires:"-1", Strict-Transport-Security:"max-age=31536000; includeSubDomains", X-Content-Type-Options:"nosniff", P3P:"CP="DSP CUR OTPi IND OTRi ONL FIN"", x-ms-request-id:"9a469a67-57dc-4f63-8c32-94a07e9d9f00", x-ms-ests-server:"2.1.10963.13 - SAN ProdSlices", Set-Cookie:"fpc=An3CgYC5t4RCuBSIOg6fMAzu_EH-AQAAANId1tYOAAAA; expires=Wed, 23-Sep-2020 20:45:06 GMT; path=/; secure; HttpOnly; SameSite=None", "x-ms-gateway-slice=prod; path=/; secure; samesite=none; httponly", "stsservicecookie=ests; path=/; secure; samesite=none; httponly", Date:"Mon, 24 Aug 2020 20:45:05 GMT", Content-Length:"1516"]>`

So if I'm correct, the O365 Multi-factor authentication is creating the issue for me here. Would there be any easy workaround for this, or is connecting with a non-MFA account the only option?

**Comment by kikovalle** [comment]
You need a non-MFA account. I cant think in an scenario where MFA makes sense with an automatic tool.
