### ISSUE TITLE
can you make this available on a different licence ?

### ISSUE THREAD

**Issue by pajura** [kikovalle/PLGSharepointRestAPI-java#47]
Hello, I was looking for a java SDK providing connection to sharepoint services and found on stackoverflow a link to yours. It looks as a nice piece of software. Would you mind releasing it using a corporate-friendlier open source license (which is btw the typical use for such code)? GPL3 is very restrictive regarding the distribution of commercial software. Basically, every piece of source code that is linked against your library, and is distributed into a product, has to be released, made available. 
Thanks,
P.

**Comment by kikovalle** [comment]
Yes its possible, just tell me about the open source license you need and ill add it to the project settings.

**Comment by pajura** [comment]
Hello, 
Thank you for your quick reply!
MIT license would be great.

**Comment by kikovalle** [comment]
From version 1.0.8 the project is under MIT license (current version in master branch)
