### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by Sachin2Dehury** [kikovalle/PLGSharepointRestAPI-java#7]
How to add it to an android project?

**Comment by kikovalle** [comment]
This is a working example of a gradle file (have not tested yet if there is no error executing the code but the imports and project build fine

    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply plugin: 'kotlin-android-extensions'
    
    android {
        compileSdkVersion 30
        buildToolsVersion "30.0.2"
    
        defaultConfig {
            applicationId "com.example.myapplication"
            minSdkVersion 26
            targetSdkVersion 30
            versionCode 1
            versionName "1.0"
            multiDexEnabled true
    
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        }
        packagingOptions {
            exclude 'META-INF/spring.tooling'
            exclude 'META-INF/spring.handlers'
            exclude 'META-INF/spring.schemas'
            exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/LICENSE'
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/license.txt'
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/NOTICE.txt'
            exclude 'META-INF/notice.txt'
            exclude 'META-INF/ASL2.0'
            exclude("META-INF/*.kotlin_module")
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-    rules.pro'
            }
        }
        compileOptions {
            coreLibraryDesugaringEnabled true
    
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
        kotlinOptions {
            jvmTarget = '1.8'
        }
    }
    repositories {
        google()
        jcenter()
        mavenLocal()
    }
    dependencies {
        coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
    
        implementation fileTree(dir: "libs", include: ["*.jar"])
        implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
        implementation 'androidx.core:core-ktx:1.1.0'
        implementation 'androidx.appcompat:appcompat:1.1.0'
        implementation 'com.google.android.material:material:1.0.0'
        implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
        implementation 'androidx.navigation:navigation-fragment-ktx:2.1.0'
        implementation 'androidx.navigation:navigation-ui-ktx:2.1.0'
    
        implementation(group: 'com.panxoloto.sharepoint.rest', name: 'PLGSharepointRestAPI', version: '1.0.1') {
            exclude group: 'commons-logging', module: 'commons-logging'
            exclude group: 'org.springframework', module: 'spring-core'
            exclude group: 'org.springframework', module: 'spring-context'
            exclude group: 'org.springframework', module: 'spring-web'
        }
    
    
        testImplementation 'junit:junit:4.12'
        implementation 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
        androidTestImplementation 'androidx.test.ext:junit:1.1.1'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    
    }

**Comment by Sachin2Dehury** [comment]
This Works.. Thank You So Much Sir.
But this is not necessary

  implementation
'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'

**Comment by Sachin2Dehury** [comment]
java.lang.NoClassDefFoundError: Failed resolution of:
Lorg/springframework/http/RequestEntity;
        at
com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.receiveSecurityToken(AuthTokenHelperOnline.java:87)
        at
com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.init(AuthTokenHelperOnline.java:139)
        at
com.panxoloto.sharepoint.rest.PLGSharepointClientOnline.<init>(PLGSharepointClientOnline.java:58)
Do I Have to use  PLGSharepointClientOnline or  PLGSharepointClient ?

**Comment by kikovalle** [comment]
Work in progress
Change implementation to use httpclient from apache httpcomponents 4.5 to make api compatible with android.

**Comment by Sachin2Dehury** [comment]
Didn't get you.

**Comment by kikovalle** [comment]
Oh sorry
I mean that i'm refactoring dependencies of my api to make it android
compatible, as i have issues on a test android project i build for testing,
and that ill text you back once its working fine.

**Comment by Sachin2Dehury** [comment]
Okay Thanks.
