### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by anusharp97** [kikovalle/PLGSharepointRestAPI-java#8]
Can you please tell how to create resource object? 
`public JSONObject uploadFile(String folder, Resource resource, JSONObject jsonMetadata, File file) throws Exception`

I tried creating a new resource object passing file path, file name. Not working.

**Comment by kikovalle** [comment]
Hello
Here is an example, this use a filesystemresource but it can be a ByteArrayResource or any kind of resource

    JSONObject metadata = new JSONObject();
    metadata.put("Title", "Proba subida");
    metadata.put("SolicitudIntervencion", "AAAAAA");
    Resource resource = new FileSystemResource(new File("PATHTOYOURFILE"));
    JSONObject result = wrapper.uploadFile("splibraryFullUri", resource, metadata);
    System.out.println(result);

Take care of the imports as it is using a Spring framework resource (i am working now in a android compatible version that will change this, but in current version it uses implementations of a spring resource):

The imports are:

    import org.springframework.core.io.FileSystemResource;
    import org.springframework.core.io.Resource;

**Comment by anusharp97** [comment]
Thanks for your quick reply.
I tried with the same format as you described.
But I am getting `500 Internal Server Error` at this particular line.
`ResponseEntity<String> responseEntity = restTemplate.exchange(requestEntity, String.class);`
Any idea on what might be going wrong?

**Comment by kikovalle** [comment]
The metadata object you pass to the api is intended to have the sharepoint internal column names you want to associate info with so you can make any search after over the library. Here is a test code i used to test the api against a sharepoint online site

	String spSiteUrl = "/YOURSITEURIPATH/";
	String user = "yourspsiteuser@domain.com";
	String passwd = "youuserpassword";
	String domain = "youspsite.sharepoint.com";

	@Test
	void test1() {
		PLGSharepointClient wrapper = new PLGSharepointClientOnline(user, passwd, domain, spSiteUrl);
		try {
			JSONObject metadata = new JSONObject();
			
			metadata.put("Title", "Title field test");
			metadata.put("Field1", "AAAAAA");

			Resource resource = new FileSystemResource(new File("/pathtoyourxlsfile.xlsx"));
			JSONObject result = wrapper.uploadFile("/FULLURIPATHTOYOURLIBRARYINCLUDINGSITEPATH", resource, metadata);
			System.out.println(result);
			Assert.assertTrue(true);
		} catch (Exception e) {
			e.printStackTrace();
			Assert.assertTrue(false);
		}
	}

The metadata you are trying to set is already set inside the api method. An internal server error might be caused maybe for sending a column you dont have defined in the library. Inside the method the correct metadata to upload a file is the one inside the method (following code is at the start of the upload method in the online implementation):

    JSONObject submeta = new JSONObject();
    submeta.put("type", "SP.ListItem");
    jsonMetadata.put("__metadata", submeta);

So the correct type to a list item file is SP.ListItem and not SP.File

Hope this helps

**Comment by anusharp97** [comment]
https://domain.sharepoint.com/sites/siteName/Lists/testList - any file uploaded to this site will be a list item.
https://domain.sharepoint.com/sites/siteName/testFolder - any file uploaded to this site is a file.
Is my understanding correct?
I think this is the part where I'm going wrong, as I'm pretty sure about metadata fields.

Not sure if SP.file is valid in java, sometime back I implemented the same in python where I used SP.File while uploading a file.
I'm a newbie in Java, correct me if wrong.

**Comment by kikovalle** [comment]
That is not java/python related, is server side types. To a fast
explanation, a file is something you can upload to a folder and a listitem
something you can put un a sp list. In this case as you arr uploadimg to a
list tje type is listitem

**Comment by anusharp97** [comment]
Thanks a lot!
I appreciate your quick responses.

**Comment by jh3129** [comment]
Hi, I'm getting a"404 not found [body]" error, but I think its down to my first paramter when calling the uploadFile() method.

/FULLURIPATHTOYOURLIBRARYINCLUDINGSITEPATH"

What would this be in your example? I've tried a few things but no joy. Thanks

**Comment by kikovalle** [comment]
with that i mean the full URI to a library/folder

For example if your site is called contoso, you have a subsite subcontoso
and a document library called My Library, that may be
"/sites/costoso/subcostoso/My Library"

**Comment by jh3129** [comment]
I see, I'm getting a 404 not found still. I suspect it is most definitely my path is wrong. Interesting...
