### ISSUE TITLE
UploadFile() method

### ISSUE THREAD

**Issue by jh3129** [kikovalle/PLGSharepointRestAPI-java#9]
Hi there just a little confused with the uploadFile() method, specifically, the Resource parameter for it.

How do I get this from "File" to a resource? I've tried putting it into a BufferedStream then casting, but no joy.

Any help appreciated. Thanks

**Comment by jh3129** [comment]
Apologies, I have just seen there are items under closed, with one similar. I will look there, thanks

**Comment by kikovalle** [comment]
I'm currently refactoring the api to make it android compatible for versions after android 23.
The trick with Resources is that as i based the design on spring restTemplate i used spring Resource as the parent of resource. This will change in future version as it will be developed using httpurlconnection.
There is a FileSystemResource from spring framework that is the correct one you may use.
Also as you say there is an example in other closed issue that was the same as this. Thats makes me think that i should refactor some of the methods to avoid confussion.
Thank you.

**Comment by jh3129** [comment]
got it working finally! Turns out my splSiteUrl needed to be a level up than what I was supplying as my folder url.
Thanks for your help, I have bought you a coffee!
